export const SET_RESULTS = 'SET_RESULTS';

export const SET_EXPO_TITLE = 'SET_EXPO_TITLE';
export const ADD_TO_EXPO = 'ADD_TO_EXPO';
export const DELETE_FROM_EXPO = 'DELETE_FROM_EXPO';
export const CLEAR_EXPO = 'CLEAR_EXPO';

export const SET_CURRENT_QUERY = 'SET_CURRENT_QUERY';

export const TOGGLE_FLOATING_BUTTON = 'TOGGLE_FLOATING_BUTTON';
